# https://docs.drone.io/pipeline/overview/
# https://docs.drone.io/pipeline/configuration/

kind: pipeline
type: docker
name: app-check

steps:
  - name: build-deps
    image: 'python:3-alpine'
    commands:
      - python -m venv .venv
      - source ./.venv/bin/activate
      - pip install -r requirements.txt
    when:
      event:
        include:
          - pull_request
  - name: pylama
    image: 'python:3-alpine'
    commands:
      - apk update > /dev/null && apk add git > /dev/null
      #- python -m venv .venv
      - source ./.venv/bin/activate
      - 'pip install pylama pylama\[all\] > /dev/null'
      - 'git --no-pager diff --name-only origin/${DRONE_TARGET_BRANCH} | xargs pylama'
    when:
      event:
        include:
          - pull_request
      branch:
        exclude: master
